import { existsSync, mkdirSync } from 'node:fs';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { promisify } from 'node:util';
import { execFile as execFileCallback, spawn } from 'node:child_process';
import { GameVisionEpisodeGate, compactSignature, selectEpisodeFrames, signatureDelta } from './game-vision-episode.mjs';
import { readActiveGameContext } from './game-context.mjs';
import { askHermsVision } from './herms-vision-gateway.mjs';
import { appendGameVisionReview } from './game-vision-review.mjs';

const execFile = promisify(execFileCallback); const ROOT = path.dirname(new URL(import.meta.url).pathname);
const CONFIG_PATH = process.env.STREAMLABELS_HERMY_CONFIG || path.join(ROOT, 'config.json');
const DEFAULTS = { output: { reactionFile: './output/hermy_reaction.txt', audioDir: './output/audio', clearAfterMs: 15000 }, tts: { enabled: true, voiceId: '', modelId: 'eleven_multilingual_v2', outputFormat: 'mp3_44100_128', apiKeyEnv: 'ELEVENLABS_API_KEY', playback: { enabled: true, command: 'ffplay', args: ['-nodisp', '-autoexit', '-loglevel', 'error', '{file}'], timeoutMs: 30000 }, voiceSettings: { stability: 0.45, similarity_boost: 0.8, style: 0.2, use_speaker_boost: true } }, gameVision: { enabled: false, device: '/dev/videoX', inputWidth: 1920, inputHeight: 1080, inputFormat: 'yuyv422', ffmpegPath: 'ffmpeg', agentId: 'your_stream_agent', sessionKey: 'your-private-vision-session', timeoutMs: 90000, baselineFps: 2, episodeFps: 5, preEventFrameCount: 10, episodeSeconds: 5, cooldownMs: 60000, maxAnalysesPerHour: 12, maxFramesPerAnalysis: 5, scoreDecayPerFrame: 1, changeThreshold: 0.16, majorChangeThreshold: 0.28, changePoints: 1, majorChangePoints: 3, triggerScore: 5, baselineWidth: 512, baselineHeight: 288, episodeWidth: 1280, episodeHeight: 720, imageCompressionQuality: 75, reactionFile: './output/game_vision_last_event.json', review: { enabled: true, dir: './output/game-vision-reviews', retain: 50 } } };
function resolveLocal(filePath) { return path.isAbsolute(filePath) ? filePath : path.join(ROOT, filePath); }
function sleep(ms) { return new Promise(resolve => setTimeout(resolve, ms)); }
const DEVICE_RETRY_MS = 5000;
async function loadConfig() { const raw = existsSync(CONFIG_PATH) ? JSON.parse(await readFile(CONFIG_PATH, 'utf8')) : {}; return { output: { ...DEFAULTS.output, ...(raw.output ?? {}) }, tts: { ...DEFAULTS.tts, ...(raw.tts ?? {}), playback: { ...DEFAULTS.tts.playback, ...((raw.tts ?? {}).playback ?? {}) }, voiceSettings: { ...DEFAULTS.tts.voiceSettings, ...((raw.tts ?? {}).voiceSettings ?? {}) } }, gameVision: { ...DEFAULTS.gameVision, ...(raw.gameVision ?? {}), review: { ...DEFAULTS.gameVision.review, ...((raw.gameVision ?? {}).review ?? {}) } } }; }
function validationErrors(cfg, requireReady = false) { const vision = cfg.gameVision; const errors = []; if (!vision.device?.trim()) errors.push('gameVision.device must name an OBS Virtual Camera V4L2 device.'); if (requireReady && !existsSync(vision.device)) errors.push(`gameVision.device is not available: ${vision.device}`); if (!vision.agentId?.trim() || vision.agentId === 'your_stream_agent') errors.push('gameVision.agentId must target your stream agent.'); if (!vision.sessionKey?.trim() || vision.sessionKey === 'your-private-vision-session') errors.push('gameVision.sessionKey must name a private vision session.'); for (const key of ['inputWidth', 'inputHeight', 'timeoutMs', 'baselineFps', 'episodeFps', 'preEventFrameCount', 'episodeSeconds', 'cooldownMs', 'maxAnalysesPerHour', 'maxFramesPerAnalysis', 'scoreDecayPerFrame', 'changeThreshold', 'majorChangeThreshold', 'changePoints', 'majorChangePoints', 'triggerScore', 'baselineWidth', 'baselineHeight', 'episodeWidth', 'episodeHeight', 'imageCompressionQuality']) if (!Number.isFinite(Number(vision[key])) || Number(vision[key]) <= 0) errors.push(`gameVision.${key} must be positive.`); if (Number(vision.majorChangeThreshold) < Number(vision.changeThreshold)) errors.push('gameVision.majorChangeThreshold must be at least gameVision.changeThreshold.'); return errors; }
async function waitForDevice(cfg) { const device = cfg.gameVision.device; let announced = false; while (!existsSync(device)) { if (!announced) { console.log(`[game-vision] idle: OBS Virtual Camera ${device} is unavailable; waiting for it to appear.`); announced = true; } await sleep(DEVICE_RETRY_MS); } if (announced) console.log(`[game-vision] OBS Virtual Camera ${device} is available; resuming.`); }
async function captureFrame(cfg, mode = 'baseline') { const vision = cfg.gameVision; if (mode === 'baseline') { const { stdout } = await execFile(vision.ffmpegPath, ['-hide_banner', '-loglevel', 'error', '-f', 'v4l2', '-framerate', '60', '-video_size', `${vision.inputWidth}x${vision.inputHeight}`, '-input_format', vision.inputFormat, '-i', vision.device, '-frames:v', '1', '-vf', 'scale=64:36,format=gray', '-f', 'rawvideo', '-pix_fmt', 'gray', 'pipe:1'], { encoding: 'buffer', maxBuffer: 256 * 1024, timeout: 5000 }); const pixels = Buffer.from(stdout); if (pixels.length !== 64 * 36) throw new Error(`FFmpeg returned an invalid baseline frame (${pixels.length} bytes).`); return { signature: compactSignature(pixels), capturedAt: new Date().toISOString(), mode }; } const width = Number(mode === 'episode' ? vision.episodeWidth : vision.baselineWidth); const height = Number(mode === 'episode' ? vision.episodeHeight : vision.baselineHeight); const { stdout } = await execFile(vision.ffmpegPath, ['-hide_banner', '-loglevel', 'error', '-f', 'v4l2', '-framerate', '60', '-video_size', `${vision.inputWidth}x${vision.inputHeight}`, '-input_format', vision.inputFormat, '-i', vision.device, '-frames:v', '1', '-vf', `scale=${width}:${height}`, '-q:v', String(Math.max(2, Math.min(31, Math.round(Number(vision.imageCompressionQuality) / 4)))), '-f', 'image2pipe', '-vcodec', 'mjpeg', 'pipe:1'], { encoding: 'buffer', maxBuffer: 8 * 1024 * 1024, timeout: 5000 }); const image = Buffer.from(stdout).toString('base64'); if (!image) throw new Error('FFmpeg returned an empty OBS Virtual Camera frame.'); return { image, width, height, capturedAt: new Date().toISOString(), mode }; }
async function publishReaction(cfg, frames, reaction) { const outputFile = resolveLocal(cfg.output.reactionFile); const eventFile = resolveLocal(cfg.gameVision.reactionFile); mkdirSync(path.dirname(outputFile), { recursive: true }); mkdirSync(path.dirname(eventFile), { recursive: true }); const rendered = `${reaction}\n`; await writeFile(outputFile, rendered); await writeFile(eventFile, `${JSON.stringify({ event: { source: 'game-vision', category: 'gameplay', type: 'vision_reaction', capturedAt: frames.at(-1)?.capturedAt, frameCount: frames.length }, reaction }, null, 2)}\n`); if (Number(cfg.output.clearAfterMs) > 0) setTimeout(() => readFile(outputFile, 'utf8').then(current => current === rendered ? writeFile(outputFile, '') : null).catch(() => {}), Number(cfg.output.clearAfterMs)).unref?.(); }
async function speakReaction(cfg, reaction) { if (!cfg.tts.enabled) return; const voiceId = cfg.tts.voiceId || process.env.ELEVENLABS_VOICE_ID; const apiKey = process.env[cfg.tts.apiKeyEnv || 'ELEVENLABS_API_KEY']; if (!voiceId || !apiKey) throw new Error('Game-vision TTS is configured but credentials are unavailable.'); const audioDir = resolveLocal(cfg.output.audioDir); mkdirSync(audioDir, { recursive: true }); const audioFile = path.join(audioDir, `${new Date().toISOString().replaceAll(/[:.]/g, '-')}-game-vision.mp3`); const url = new URL(`https://api.elevenlabs.io/v1/text-to-speech/${encodeURIComponent(voiceId)}/stream`); url.searchParams.set('output_format', cfg.tts.outputFormat); const response = await fetch(url, { method: 'POST', headers: { accept: 'audio/mpeg', 'content-type': 'application/json', 'xi-api-key': apiKey }, body: JSON.stringify({ text: reaction, model_id: cfg.tts.modelId, voice_settings: cfg.tts.voiceSettings }) }); if (!response.ok) throw new Error(`Game-vision TTS failed with HTTP ${response.status}.`); await writeFile(audioFile, Buffer.from(await response.arrayBuffer())); if (!cfg.tts.playback.enabled) return; const child = spawn(cfg.tts.playback.command, cfg.tts.playback.args.map(arg => arg === '{file}' ? audioFile : arg), { cwd: ROOT, env: process.env, stdio: ['ignore', 'ignore', 'pipe'] }); await new Promise((resolve, reject) => { const timeout = setTimeout(() => { child.kill('SIGTERM'); reject(new Error('Game-vision TTS playback timed out.')); }, Number(cfg.tts.playback.timeoutMs) || 30000); child.on('error', reject); child.on('close', code => { clearTimeout(timeout); code === 0 ? resolve() : reject(new Error(`Game-vision TTS playback exited ${code}.`)); }); }); }
async function captureEpisode(cfg) { const frames = []; const deadline = Date.now() + Number(cfg.gameVision.episodeSeconds) * 1000; while (Date.now() < deadline) { const startedAt = Date.now(); frames.push(await captureFrame(cfg, 'episode')); const remaining = (1000 / Number(cfg.gameVision.episodeFps)) - (Date.now() - startedAt); if (remaining > 0) await sleep(remaining); } return selectEpisodeFrames([], frames, Number(cfg.gameVision.maxFramesPerAnalysis)); }
async function writeReview(cfg, candidate, selected, { visionStatus, ttsStatus, reaction = '' }) { const review = cfg.gameVision.review; if (!review?.enabled) return; await appendGameVisionReview({ directory: resolveLocal(review.dir), retain: review.retain, record: { trigger: { outcome: 'triggered', pixelDelta: candidate.delta, score: candidate.score, cooldownMs: cfg.gameVision.cooldownMs, thresholds: { change: cfg.gameVision.changeThreshold, majorChange: cfg.gameVision.majorChangeThreshold, triggerScore: cfg.gameVision.triggerScore } }, selectedFrames: { count: selected.length, timestamps: selected.map(frame => frame.capturedAt) }, vision: { status: visionStatus }, tts: { status: ttsStatus }, reaction } }); }
async function run(cfg) { const errors = validationErrors(cfg); if (errors.length) throw new Error(errors.join(' ')); let gate = new GameVisionEpisodeGate(cfg.gameVision); const analyses = []; for (;;) { await waitForDevice(cfg); const startedAt = Date.now(); try { const frame = await captureFrame(cfg); const candidate = gate.observe(frame); const hourAgo = Date.now() - 3600000; while (analyses.length && analyses[0] < hourAgo) analyses.shift(); if (candidate.triggered && analyses.length < Number(cfg.gameVision.maxAnalysesPerHour)) { const selected = await captureEpisode(cfg); let reaction = ''; let visionStatus = 'failed'; let ttsStatus = 'not_needed'; try { reaction = await askHermsVision({ frames: selected, gameContext: await readActiveGameContext(), config: cfg.gameVision }); visionStatus = reaction && !/^silent[.!]*$/i.test(reaction) ? 'reaction' : 'silent'; } catch (error) { console.error(`[game-vision] vision failed: ${error.message}`); } analyses.push(Date.now()); if (reaction && !/^silent[.!]*$/i.test(reaction)) { await publishReaction(cfg, selected, reaction); try { await speakReaction(cfg, reaction); ttsStatus = 'played'; } catch (error) { ttsStatus = 'failed'; console.error(`[game-vision] TTS failed: ${error.message}`); } } await writeReview(cfg, candidate, selected, { visionStatus, ttsStatus, reaction }); } } catch (err) { if (existsSync(cfg.gameVision.device)) throw err; console.log(`[game-vision] OBS Virtual Camera ${cfg.gameVision.device} disappeared; returning to idle.`); gate = new GameVisionEpisodeGate(cfg.gameVision); continue; } const remaining = (1000 / Number(cfg.gameVision.baselineFps)) - (Date.now() - startedAt); if (remaining > 0) await sleep(remaining); } }
const cfg = await loadConfig(); if (process.argv.includes('--validate')) { const errors = validationErrors(cfg, true); console.log(JSON.stringify({ ok: errors.length === 0, enabled: Boolean(cfg.gameVision.enabled), device: cfg.gameVision.device, agentId: cfg.gameVision.agentId, errors }, null, 2)); process.exitCode = errors.length ? 1 : 0; } else if (!cfg.gameVision.enabled) { console.error('gameVision is disabled. Set gameVision.enabled to true after validation.'); process.exitCode = 2; } else run(cfg).catch(err => { console.error(`[game-vision] fatal: ${err.message}`); process.exitCode = 1; });
